version: '3.8'

services:
  mock_api:
    image: jordimartin/mmock
    ports:
      - 8082:8082
      - 8083:8083
    volumes:
      - ./mocks:/config

  proxy:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./templates:/etc/nginx/templates
