# install vscode extention https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:8083/?name=bob

###

GET http://localhost:80/health

###

GET http://localhost:443/v2

