# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: ecr-proxy

on:
  push:
  release:
    types: [published, created, edited]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: restore
      run: |
        pip install invoke
        invoke restore
    - name: start test env
      run: invoke start -d
    - name: run tests
      run: |
        invoke tests
        invoke stop

  publish:
    runs-on: ubuntu-latest
    needs: ci
    steps:
        # if: github.event_name = 'release'
      - name: Push to GitHub Packages 
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: caseyburns/ecr-proxy
          tag_with_ref: true
